# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mrboard < Formula
  desc "GitLab MR review board for daily standups"
  homepage "https://github.com/ceffo/mrboard"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ceffo/mrboard/releases/download/v0.0.1/mrboard_0.0.1_darwin_amd64.tar.gz"
      sha256 "721c5c99e110dd74b9f4b880cbfa4d753e8066ad69a672314be7e0f61a361bfa"

      define_method(:install) do
        bin.install "mrboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ceffo/mrboard/releases/download/v0.0.1/mrboard_0.0.1_darwin_arm64.tar.gz"
      sha256 "62cab65e83bf847d52968e54bacc02b5286fd5d2a15016f9fd743937117257f3"

      define_method(:install) do
        bin.install "mrboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/mrboard/releases/download/v0.0.1/mrboard_0.0.1_linux_amd64.tar.gz"
      sha256 "494fa93443d2d6d459d1676f52d4bd10db09aaf771a3a68ebe7491021c7adef6"
      define_method(:install) do
        bin.install "mrboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/mrboard/releases/download/v0.0.1/mrboard_0.0.1_linux_arm64.tar.gz"
      sha256 "bb6a6b83bbe05e16dd9ac7c27ead7a4724324ddf5549fc643e7fd1ce3a545086"
      define_method(:install) do
        bin.install "mrboard"
      end
    end
  end

  test do
    system "#{bin}/mrboard", "version"
  end
end
