# This file was generated by GoReleaser. DO NOT EDIT.
cask "mrboard" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "99d11beec84f467f99df8dc9cbc05d9d6d047420be3ab269e0fa34f4b38b1624"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9d9027d62f0dcd7e9748385a250f5daedf4c5cf0b30cf012467b13adb6ac01b9"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d728d3a6220be464d96bef026177df1467af5ddd355f645bb6030266f66ac155"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4cb3b54c9015dd7363278d8bda15226e0ad26d878da5a3f8c08538a030d4f8d"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mrboard"
  desc "GitLab MR review board for daily standups"
  homepage "https://github.com/ceffo/mrboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mrboard"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mrboard"]
  end

  generate_completions_from_executable "mrboard",
    base_name: "mrboard",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
