# This file was generated by GoReleaser. DO NOT EDIT.
cask "mrboard" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "899945b23630767f5b8849b13d7bed1bc68ebf398240f0d58cacbad978aa4c4b"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a69f646786fedc2a12257e37f011341d8d31144fd6acfd5d87973b4b5bb930d"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "782928fdae4771ff4b4e0c3475a083a4527ccbc04fae6bd4a616706fc9bb2e04"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2614e93d933f06cb19f24b1fe8c232eaac70b059d008a5c0b6693bc4ae890cce"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mrboard"
  desc "GitLab MR review board for daily standups"
  homepage "https://github.com/ceffo/mrboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mrboard"
  generate_completions_from_executable "mrboard", "completion",
    base_name: "mrboard",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mrboard"]
  end

  # No zap stanza required

end
