# This file was generated by GoReleaser. DO NOT EDIT.
cask "mrboard" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "7e60e6fa3758715686cc3bd58639be27be5e756372fa6035fb91f2c69e52724a"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a1b4bad6300a0e32a7a0a34c1a3e5198628f63f3c24a1360cb1ef65afca29d5"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "08fec038ec79a6189fd662f6ca9a421daebe88754e759542d170879bdcc9348f"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6dce9eaa49868d3316ea6bae2bb9e3080f208daceed1899d53cc232b12024ab5"
      url "https://github.com/ceffo/mrboard/releases/download/v#{version}/mrboard_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mrboard"
  desc "GitLab MR review board for daily standups"
  homepage "https://github.com/ceffo/mrboard"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mrboard"

  preflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mrboard"]
  end

  generate_completions_from_executable "mrboard",
    base_name: "mrboard",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
