# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GumCeffo < Formula
  desc "Fork of charmbracelet/gum, a tool for glamorous shell scripts"
  homepage "https://github.com/ceffo/gum"
  version "2.0.2-ceffo.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ceffo/gum/releases/download/v2.0.2-ceffo.1/gum_2.0.2-ceffo.1_darwin_amd64.tar.gz"
      sha256 "58dc43a128f9ecaa394831897497fc103ff05ce1545c82b41a162ad2f534b57c"

      define_method(:install) do
        bin.install "gum"
        generate_completions_from_executable(bin/"gum", "completion")
        (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ceffo/gum/releases/download/v2.0.2-ceffo.1/gum_2.0.2-ceffo.1_darwin_arm64.tar.gz"
      sha256 "f70f7de9acd42db5ed9bb8b884778ab2f56456ead02db57f3aa152137f76afce"

      define_method(:install) do
        bin.install "gum"
        generate_completions_from_executable(bin/"gum", "completion")
        (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/gum/releases/download/v2.0.2-ceffo.1/gum_2.0.2-ceffo.1_linux_amd64.tar.gz"
      sha256 "7add0f317ee6698f87f28d1a33eaadd0cfef8ad17f22e0cc4af6da97c0da2ccc"
      define_method(:install) do
        bin.install "gum"
        generate_completions_from_executable(bin/"gum", "completion")
        (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/gum/releases/download/v2.0.2-ceffo.1/gum_2.0.2-ceffo.1_linux_arm64.tar.gz"
      sha256 "b5f9fa4acf0e0a14686c223aaf06ed042d8c2a7677f5677e6148f0784dbcfb2f"
      define_method(:install) do
        bin.install "gum"
        generate_completions_from_executable(bin/"gum", "completion")
        (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
      end
    end
  end

  conflicts_with "gum"

  test do
    assert_match "gum version", shell_output("#{bin}/gum --version")
  end
end
