# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gum < Formula
  desc "Fork of charmbracelet/gum, a tool for glamorous shell scripts"
  homepage "https://github.com/ceffo/gum"
  version "2.0.2-ceffo.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ceffo/gum/releases/download/v2.0.2-ceffo.2/gum_2.0.2-ceffo.2_darwin_amd64.tar.gz"
      sha256 "c565cad30b977914bd8f6d645b4195c40b3e469e6152976d9d922b380382c201"

      define_method(:install) do
        bin.install "gum"
        generate_completions_from_executable(bin/"gum", "completion")
        (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ceffo/gum/releases/download/v2.0.2-ceffo.2/gum_2.0.2-ceffo.2_darwin_arm64.tar.gz"
      sha256 "549541b30c9fefea550b1dee512dd1719b5803725e61a5ad03eb5cb90e2d16bf"

      define_method(:install) do
        bin.install "gum"
        generate_completions_from_executable(bin/"gum", "completion")
        (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/gum/releases/download/v2.0.2-ceffo.2/gum_2.0.2-ceffo.2_linux_amd64.tar.gz"
      sha256 "40c345f7bbe26f121f45c64b07c972db62341ce9774a8d6407666fe763fcfd61"
      define_method(:install) do
        bin.install "gum"
        generate_completions_from_executable(bin/"gum", "completion")
        (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/gum/releases/download/v2.0.2-ceffo.2/gum_2.0.2-ceffo.2_linux_arm64.tar.gz"
      sha256 "ae437de3e3c84ab02972b110004d8b6f9b5b0446d13d923f195d273b369220f7"
      define_method(:install) do
        bin.install "gum"
        generate_completions_from_executable(bin/"gum", "completion")
        (man1/"gum.1").write Utils.safe_popen_read(bin/"gum", "man")
      end
    end
  end

  test do
    assert_match "gum version", shell_output("#{bin}/gum --version")
  end
end
