# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mrboard < Formula
  desc "GitLab MR review board for daily standups"
  homepage "https://github.com/ceffo/mrboard"
  version "0.17.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ceffo/mrboard/releases/download/v0.17.2/mrboard_0.17.2_darwin_amd64.tar.gz"
      sha256 "a8c919ccfbca5da4d91c1f95d4242e87f300c5cabc0cb7b32ec4f1a1f61d72a6"

      define_method(:install) do
        bin.install "mrboard"
        # shell_parameter_format: :cobra already appends `completion <shell>` to the
        # invocation. Do not pass "completion" as an explicit command arg here — that
        # duplicates it, invoking `mrboard completion completion <shell>` and printing
        # cobra's help text instead of a real completion script (regressed twice: #1).
        generate_completions_from_executable(bin/"mrboard",
                                              shell_parameter_format: :cobra,
                                              shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ceffo/mrboard/releases/download/v0.17.2/mrboard_0.17.2_darwin_arm64.tar.gz"
      sha256 "6e1d2f457c4053abe24156b362a6d3f2e7dfd4a4c89f2239a50f3a5df639b2a1"

      define_method(:install) do
        bin.install "mrboard"
        # shell_parameter_format: :cobra already appends `completion <shell>` to the
        # invocation. Do not pass "completion" as an explicit command arg here — that
        # duplicates it, invoking `mrboard completion completion <shell>` and printing
        # cobra's help text instead of a real completion script (regressed twice: #1).
        generate_completions_from_executable(bin/"mrboard",
                                              shell_parameter_format: :cobra,
                                              shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/mrboard/releases/download/v0.17.2/mrboard_0.17.2_linux_amd64.tar.gz"
      sha256 "cfb0f8aa3694b4fdc521a8eb915c21c291b3e7e93a271bc264357c144956c0bb"
      define_method(:install) do
        bin.install "mrboard"
        # shell_parameter_format: :cobra already appends `completion <shell>` to the
        # invocation. Do not pass "completion" as an explicit command arg here — that
        # duplicates it, invoking `mrboard completion completion <shell>` and printing
        # cobra's help text instead of a real completion script (regressed twice: #1).
        generate_completions_from_executable(bin/"mrboard",
                                              shell_parameter_format: :cobra,
                                              shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/mrboard/releases/download/v0.17.2/mrboard_0.17.2_linux_arm64.tar.gz"
      sha256 "144ecc1af0c6cafeb5eff1c25f196ae16ccfd2d9269ff6d150a56758164a1178"
      define_method(:install) do
        bin.install "mrboard"
        # shell_parameter_format: :cobra already appends `completion <shell>` to the
        # invocation. Do not pass "completion" as an explicit command arg here — that
        # duplicates it, invoking `mrboard completion completion <shell>` and printing
        # cobra's help text instead of a real completion script (regressed twice: #1).
        generate_completions_from_executable(bin/"mrboard",
                                              shell_parameter_format: :cobra,
                                              shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/mrboard", "--version"
  end
end
