# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mrboard < Formula
  desc "GitLab MR review board for daily standups"
  homepage "https://github.com/ceffo/mrboard"
  version "0.16.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ceffo/mrboard/releases/download/v0.16.0/mrboard_0.16.0_darwin_amd64.tar.gz"
      sha256 "1268bc0994609d2553e9bc5eadbc7b7aa6cf67b024ad2461f823015fbdfe2eb6"

      define_method(:install) do
        bin.install "mrboard"
        generate_completions_from_executable(bin/"mrboard", "completion",
                                              shell_parameter_format: :cobra,
                                              shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ceffo/mrboard/releases/download/v0.16.0/mrboard_0.16.0_darwin_arm64.tar.gz"
      sha256 "02450df752099bfb4f40b1c3e99c254cd645d192d737c8c5d3f1b9b7fc1b1938"

      define_method(:install) do
        bin.install "mrboard"
        generate_completions_from_executable(bin/"mrboard", "completion",
                                              shell_parameter_format: :cobra,
                                              shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/mrboard/releases/download/v0.16.0/mrboard_0.16.0_linux_amd64.tar.gz"
      sha256 "179e8552bec8cf6d63f06c950ec0cb8cef93ab7bf50a0e50718f6085e941b727"
      define_method(:install) do
        bin.install "mrboard"
        generate_completions_from_executable(bin/"mrboard", "completion",
                                              shell_parameter_format: :cobra,
                                              shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ceffo/mrboard/releases/download/v0.16.0/mrboard_0.16.0_linux_arm64.tar.gz"
      sha256 "3015e52347ef2b086fe2d6e24c689a49fef0f27fc0d913b524d6d9c9b940747f"
      define_method(:install) do
        bin.install "mrboard"
        generate_completions_from_executable(bin/"mrboard", "completion",
                                              shell_parameter_format: :cobra,
                                              shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/mrboard", "--version"
  end
end
